Document: libmoflow
Title: Debian libmoflow Manual
Author: <insert document author here>
Abstract: This manual describes what libmoflow is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libmoflow/libmoflow.sgml.gz

Format: postscript
Files: /usr/share/doc/libmoflow/libmoflow.ps.gz

Format: text
Files: /usr/share/doc/libmoflow/libmoflow.text.gz

Format: HTML
Index: /usr/share/doc/libmoflow/html/index.html
Files: /usr/share/doc/libmoflow/html/*.html

  
